const DataBase = [
    ['留言板','User-Generated Content','/14/tools/issues','search/talk.webp',true],
    ['附中电子铃声新版（bellfz3）','北京师大附中的电子铃声。','/14/tools/clock/fz3','search/bell.png'],
    ['附中电子铃声（无下课铃）（bellfz2）','北京师大附中电子铃声，没有下课铃。','/14/tools/clock/fz2','search/bell.png'],
    ['附中电子铃声（bellfz1）','北京师大附中的电子铃声。','/14/tools/clock/fz1','search/bell.png'],
    ['钢琴（piano）','可以模拟钢琴，把键盘当钢琴','/14/tools/piano','search/music.png'],
    ['台球','戴德隆快来','/14/games/desk-ball','search/taiqiu.png'],
    ['五子棋','JZQ&HYG快来','/14/games/5-chess/','search/5-chess.jpg'],
    ['打败王梓豪2（pkwzh2）','可用于训练数学整式加减。','/14/games/pkwzh2/','search/math.png'],
    ['时钟（clock)','电子时钟，可以放到Kindle上。','/14/tools/clock','search/clock.png'],
    ['时钟（黑色）','电子时钟，可以放到Kindle上。','/14/tools/clock/black','search/clock.png'],
    ['求最大公因数（gcd）','计算两个数的最大公因数','/14/math/gcd','search/gcd.png',true],
    ['互联网大厂裁员（fire）','时政述评：互联网大厂裁员','https://kevinwu521.gitee.io/res/szsp.pptx','search/bigfire.png'],
    ['快问快答（quickqa）','#游戏（games）','/14/games/quickqa','search/ques.png'],
    ['找不同（super）','#游戏（games）','/14/games/super','search.jpeg'],
    ['有理数复盘（youlishu）','#个人（persoal）','/14/person/youlishu','search/math.png',true],
    ['音效（sound）','#工具（tools）','/14/tools/sound','search/music.png'],
    ['查看网站的404页面','这个网站的404页面很好玩，不信你看看。','/404.html','search/404.png',true],
    ['登录后台','','/14/control/back','search/vscode.png',true]
];